### ISSUE TITLE
Insecure facsimile request - Page image not loading on Production

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/textlab#227] opened 2020-07-16 15:40 UTC
Page is not loading on https://app.textlab.org/

![image](https://user-images.githubusercontent.com/18423533/87690641-b3274980-c757-11ea-846f-5b8c7a8f80fa.png)

**Comment by timdunn22** [comment] 2020-07-25 15:34
Duplicate of #228

**Closed** 2021-01-05 14:51 UTC
Labels: CLIN0002, bug
